### PR TITLE
Fixes Paywall and Customer Center transition animations on iOS

### LINKED ISSUE #398: The paywall on iOS is displayed outside the horizontal bounds, and only the first horizontal half is visible
- [x] I have updated Purchases SDK to the latest version
- [X] I have read
  the [Contribution Guidelines](https://github.com/RevenueCat/purchases-android/blob/main/CONTRIBUTING.md)
- [X] I have searched the [Community](https://community.revenuecat.com)
- [X] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [X] I have searched
  for [existing Github issues](https://github.com/RevenueCat/purchases-kmp/issues)

**Describe the bug**
The paywall on iOS is displayed outside the horizontal bounds, and only the first horizontal half is visible. Sometimes it displays correctly only when displaying the paywall for the first time after the app launches; otherwise, it always looks too wide. On Android, it displays correctly.

1. Environment
    1. Platform: iOS
    2. SDK version: 1.7.8+13.32.0
    3. OS version: iOS 18.5
    4. IDE (e.g. Android Studio, Xcode, Fleet): Android Studio and Xcode
    5. IDE version: AS 2024.3.2, XC 16.3 (16E140)
    6. Device and/or emulator/simulator:
        - [X] Device: iPhone 14 Pro Max, iPhone 11
    7. Environment:
        - [X] Closed testing / Sandbox
        - [X] TestFlight
        - [X] Production
    8. How widespread is the issue. Percentage of devices affected. 100%
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue N/A
3. Steps to reproduce, with a description of expected vs. actual behavior
     Open the app, launch the Paywall. Expected: Paywall should display correctly, the same as on Android. Actual: Paywall is displayed out of display bounds.
5. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to   have context, eg. stackoverflow, etc.)
Check the attached screenshots.

Android Paywall
Image

iOS Paywall
Image

### PR DESCRIPTION
**Pull request by JayShortway**
## Bug
There's a long standing bug where UIKit views are not rendered properly when they use position-based transition animations (e.g. slide in). This affects both Paywalls and Customer Center.

## Fix
This PR fixes that by updating the Compose constraints on the UIKit side using `NSLayoutConstraint`, in a new `layoutViewController()` modifier. 

| Before | After |
|-------|------|
| https://github.com/user-attachments/assets/01117e6b-a705-4bc1-8961-043ad0270fae |  https://github.com/user-attachments/assets/9c868d15-2561-46ea-ab77-33fd7ce4c730 |
| https://github.com/user-attachments/assets/4fa36f31-2348-43d2-9729-3efb2ede1e35 | https://github.com/user-attachments/assets/b5db47ad-262b-42c8-83ca-4d4ea66f2c5e |

Fixes #398, #358, #287

### CODE REVIEW

File: revenuecatui/src/iosMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/ConstrainingViewController.kt [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+    }
+
+    private fun CValue<CGRect>.satisfy(constraints: Constraints): CValue<CGRect> = useContents {
+        CGRectMake(
+            x = origin.x,
+            y = origin.y,
+            width = constraints.fixedWidthPt ?: size.width,
+            height = constraints.fixedHeightPt ?: size.height,
+        )
+    }
```
Comment (JayShortway) [inline revenuecatui/src/iosMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/ConstrainingViewController.kt]: This is the fix.

Comment (ajpallares) [reply revenuecatui/src/iosMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/ConstrainingViewController.kt]: 🤔 I'm not really sure `viewWillLayoutSubviews()` is the best place for this. Could this potentially cause an infinite loop? (like `viewWillLayoutSubviews()` makes the view frame change, then this view frame change triggers a new `viewWillLayoutSubviews()` call, and so on). I've seen some infinite loops of this kind with with `layoutSubviews()` (not that I remember any with `viewWillLayoutSubviews()` tbh).

Now, since this fully seems to depend on the `constraints` variable, why not use iOS `NSLayoutConstraints` instead? If I'm understanding the code correctly, we only care about the fixedWidth and fixedHeight values of the constraints object. Don't know if this is possible, but could we react when `var constraints` changes so that we:
1. Invalidate the previously-stored `NSLayoutConstrains` array
2. Create, activate and store a new `NSLayoutConstraints` array (based on `constraints.fixedWidthPt` and `constraints.fixedHeightPt`, i.e. if `constraints.fixedWidthPt` is `null`, do not add a fixed width constraint, and similar if `constraints.fixedHeightPt` is `null`)

My experience in the past has been that working with frames in `viewWillLayoutSubviews` and similar methods is flaky, whereas using `NSLayoutConstraints` has been very reliable.

Also, if you take this approach, you make sure you execute the updateNSLayoutConstraints logic in `viewDidLoad()` as well, as it might happen that the `constraints` var is set before the `view` is loaded.

WDYT?

**Review by ajpallares — COMMENTED** [review]
Wow, nice work fixing these issues! I can mostly add value regarding the iOS code. Please, see my comment with a proposal to use `NSLayoutConstraints` instead. Let me know what you think!

File: revenuecatui/src/iosMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/ConstrainingViewController.kt [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+
+        view.setFrame(view.frame.satisfy(currentConstraints))
+    }
+
+    private fun CValue<CGRect>.satisfy(constraints: Constraints): CValue<CGRect> = useContents {
+        CGRectMake(
+            x = origin.x,
+            y = origin.y,
+            width = constraints.fixedWidthPt ?: size.width,
+            height = constraints.fixedHeightPt ?: size.height,
```
Comment (tonidero) [inline revenuecatui/src/iosMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/ConstrainingViewController.kt]: Just in case, have you tested the fix on footer paywalls both loaded, and the transition from loading to loaded?

**Review by tonidero — COMMENTED** [review]
No other real comments aside from existing ones. But nice work on this!!

File: revenuecatui/src/iosMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/ConstrainingViewController.kt (hunk 1 above)
Comment (JayShortway) [reply revenuecatui/src/iosMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/ConstrainingViewController.kt]: Amazing, thank you! This is exactly why I requested your review specifically 😄 Will have a look.

File: revenuecatui/src/iosMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/ConstrainingViewController.kt (hunk 2 above)
Comment (JayShortway) [reply revenuecatui/src/iosMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/ConstrainingViewController.kt]: Great callout! I added a toggle to the sample app to test this more easily. 

It still works: 

https://github.com/user-attachments/assets/1ff70342-38ba-4907-a302-cada62adb98a

File: revenuecatui/src/iosMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/ConstrainingViewController.kt (hunk 1 above)
Comment (JayShortway) [reply revenuecatui/src/iosMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/ConstrainingViewController.kt]: I moved all of the layout logic into the new custom `layoutViewController()` modifier, and the `LayoutViewController` Modifier Node. This greatly simplified both `UIKitPaywall` and `UIKitCustomerCenter`.

Comment (JayShortway) [reply revenuecatui/src/iosMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/ConstrainingViewController.kt]: @ajpallares Thanks again for all your help! 🙌 🫶

File: revenuecatui/src/iosMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/modifier/layoutViewController.kt [hunk 3]
```diff
@@ -0,0 +1,146 @@
...
+        constraints: Constraints,
+    ): MeasureResult {
+        // Check if we are being asked to wrap our own content height. If so, we will use the
+        // measurement done by UIKit.
+        val constraintsToUse = if (!constraints.hasFixedHeight)
+            intrinsicContentHeightProvider()
+                .roundToPx()
+                .coerceAtMost(constraints.maxHeight)
+                .let { height -> constraints.copy(minHeight = height, maxHeight = height) }
+        else constraints
```
Comment (ajpallares) [inline revenuecatui/src/iosMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/modifier/layoutViewController.kt]: Would it ever be needed to do the same for the width? I'm mostly thinking on iPad, where a paywall could potentially not cover the whole screen width.

**Review by ajpallares — APPROVED** [review]
We did end up with a very clean solution. Great job! 👏

File: revenuecatui/src/iosMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/modifier/layoutViewController.kt (hunk 3 above)
Comment (JayShortway) [reply revenuecatui/src/iosMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/modifier/layoutViewController.kt]: Good point! Can't hurt. Added here: https://github.com/RevenueCat/purchases-kmp/pull/427/commits/4e5cbff19f0c5c0a818c456bddadac581c0c06a5.
